### ISSUE TITLE
className fixes

### ISSUE THREAD

**Issue by MonkeysAtWork** [yurasovm/eCSStractor-for-VSCode#6]
Здравствуйте, плагин не работает с jsx и classNames, есть PR с исправлениями, судя по датам, висит давно... Исправьте пожулуйста)

**Comment by MonkeysAtWork** [comment]
ds

**Comment by tagir-developer** [comment]
If "className" do not working in jsx, you must:

1) Go to extension folder  **C:/User/.vscode/extensions/diz.ecsstractor-port-0.0.3/extension.js**

2) **Replace this expression**     

`processedEls.filter((el) => { return typeof el.attribs.class !== 'undefined' && el.attribs.class.trim() !== ''; }).forEach(el => { var cssClasses = el.attribs.class.split(' ').filter(className => className.trim() !== ''); cssClasses.forEach(cssClass => { if (outputClasses.indexOf(cssClass) === -1) { outputClasses.push(cssClass); } }); }); `

**with this** 

```
const attribName = 'classname' // use 'class' if you need

processedEls.filter((el) => { return typeof el.attribs[attribName] !== 'undefined' && el.attribs[attribName].trim() !== ''; }).forEach(el => { var cssClasses = el.attribs[attribName].split(' ').filter(className => className.trim() !== ''); cssClasses.forEach(cssClass => { if (outputClasses.indexOf(cssClass) === -1) { outputClasses.push(cssClass); } }); });
```
